### ISSUE TITLE
Version dismatch and "Already added" Dexer error

### ISSUE THREAD

**Issue by DouglasHennrich** [yozef/FusedLocation#1]
I believe that the version compiled for this module doesn't exists
`Titanium Mobile SDK 6.1.0.GA`
The latest version(until now) is `6.0.2.GA`

I have changed on mainfest to 6.0.2.GA and when I compile it I get these errors:
```
[ERROR] Failed to run dexer:
[ERROR]   
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/GoogleSignInAccount;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/GoogleSignInAccount$1;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/GoogleSignInOptions;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/GoogleSignInOptions$1;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/GoogleSignInOptions$Builder;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/internal/zze;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/zza;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/zzb;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ConnectionResult;
[ERROR]   
[ERROR] UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] java.lang.RuntimeException: Translation has been interrupted
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR]         at com.android.dx.command.dexer.Main.runMultiDex(Main.java:366)
[ERROR]         at com.android.dx.command.dexer.Main.run(Main.java:275)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR]         at com.android.dx.command.Main.main(Main.java:106)
[ERROR] Caused by: java.lang.InterruptedException: Too many errors
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR]         ... 4 more
```

I only have your module installed.

Thanks

**Comment by yozef** [comment]
Released https://github.com/yozef/FusedLocation/releases/tag/1.2.3
Min SDK is now 6.0.0
